apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-demo-staging
  namespace: openshift-gitops
spec:
  destination:
    namespace: dotnet-demo-staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 02-SHIP/gitops/gitops-app/overlays/staging
    repoURL: https://github.com/RedHatNetherlandsSA/ocp-devex-demos.git
    targetRevision: main
  ignoreDifferences:
  - group: route.openshift.io
    jsonPointers:
      - /spec/host
      - /status/ingress
    kind: Route
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true