apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: coolstore-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: catalog-default
  namespace: coolstore-catalog
spec:
  hosts:
    - $GATEWAY_URL
  gateways:
    - istio-system/coolstore-gateway
  http:
    - name: default-route
      match:
        - uri:
            exact: /services/products
        - uri:
            exact: /services/product
        - uri:
            exact: /
      route:
        - destination:
            host: catalog
            port:
              number: 8080
    - name: frontend-route
      match:
        - uri:
            prefix: /catalog
      rewrite:
        uri: /
      route:
        - destination:
            host: catalog
            port:
              number: 8080