apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  broker:
    defaultConfig:
      authSecretName: ''
      bootstrapServers: >-
        my-cluster-kafka-bootstrap.knative-kafka.svc:9091,my-cluster-kafka-bootstrap.knative-kafka.svc:9092,my-cluster-kafka-bootstrap.knative-kafka.svc:9093
      numPartitions: 6
      replicationFactor: 3
    enabled: true
  channel:
    authSecretName: ''
    authSecretNamespace: ''
    bootstrapServers: >-
      my-cluster-kafka-bootstrap.knative-kafka.svc:9091,my-cluster-kafka-bootstrap.knative-kafka.svc:9092,my-cluster-kafka-bootstrap.knative-kafka.svc:9093
    enabled: true
  high-availability:
    replicas: 1
  sink:
    enabled: true
  source:
    enabled: true

