apiVersion: v1
data:
  database-name: aW52ZW50b3J5
  database-password: bXlzZWNyZXRwYXNzd29yZA==
  database-user: aW52ZW50b3J5
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: postgresql-ephemeral-template
  name: inventory-database
type: Opaque
