apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: gitops-demo-staging

patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: dotnet-demo
  path: patch-deployment.yaml