apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: dotnet-demo-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 03-ocp-gitops/gitops-app
    repoURL: https://github.com/adnan-drina/ocp-devex-demos.git
    targetRevision: main
  ignoreDifferences:
  - group: route.openshift.io
    jsonPointers:
      - /spec/host
      - /status/ingress
    kind: Route
  syncPolicy:
    automated:
      prune: true
      selfHeal: true