apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-fault-delay
  namespace: coolstore-inventory
spec:
  hosts:
    - inventory
  http:
    - fault:
        delay:
          fixedDelay: 5s
          percentage:
            value: 10
      route:
        - destination:
            host: inventory
            port:
              number: 80