apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-fault
  namespace: coolstore-inventory
spec:
  hosts:
    - inventory
  http:
    - fault:
        abort:
          httpStatus: 500
          percentage:
            value: 10
      route:
        - destination:
            host: inventory
            port:
              number: 80