apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coolstore-service
  namespace: coolstore-inventory
spec:
  hosts:
    - inventory
  http:
    - route:
        - destination:
            host: inventory
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-database
  namespace: coolstore-inventory
spec:
  hosts:
    - inventory-database
  http:
    - route:
        - destination:
            host: inventory-database
            port:
              number: 5432