bases:
- ../../base

namePrefix: prod-
namespace: gitops-demo-production

patchesJson6902:
  - target:
      version: v1
      group: apps.openshift.io
      kind: Deployment
      name: dotnet-demo
    path: patch-deployment.yaml