apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-demo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: dotnet-demo
          image: quay.io/adrina/dotnet-demo:main